// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commands.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCommand = `-- name: CreateCommand :one
INSERT INTO commands (device_id, action, payload, status, issued_by)
VALUES ($1, $2, $3, 'pending', $4)
RETURNING id, device_id, action, payload, status, issued_by, issued_at, sent_at, ack_at, error_message
`

type CreateCommandParams struct {
	DeviceID uuid.UUID       `db:"device_id" json:"device_id"`
	Action   string          `db:"action" json:"action"`
	Payload  json.RawMessage `db:"payload" json:"payload"`
	IssuedBy pgtype.UUID     `db:"issued_by" json:"issued_by"`
}

func (q *Queries) CreateCommand(ctx context.Context, arg CreateCommandParams) (Command, error) {
	row := q.db.QueryRow(ctx, createCommand,
		arg.DeviceID,
		arg.Action,
		arg.Payload,
		arg.IssuedBy,
	)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Action,
		&i.Payload,
		&i.Status,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.SentAt,
		&i.AckAt,
		&i.ErrorMessage,
	)
	return i, err
}

const getCommandByID = `-- name: GetCommandByID :one
SELECT id, device_id, action, payload, status, issued_by, issued_at, sent_at, ack_at, error_message FROM commands WHERE id = $1
`

func (q *Queries) GetCommandByID(ctx context.Context, id uuid.UUID) (Command, error) {
	row := q.db.QueryRow(ctx, getCommandByID, id)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Action,
		&i.Payload,
		&i.Status,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.SentAt,
		&i.AckAt,
		&i.ErrorMessage,
	)
	return i, err
}

const listRecentCommandsByDevice = `-- name: ListRecentCommandsByDevice :many
SELECT id, device_id, action, payload, status, issued_by, issued_at, sent_at, ack_at, error_message FROM commands
WHERE device_id = $1
ORDER BY issued_at DESC
LIMIT $2
`

type ListRecentCommandsByDeviceParams struct {
	DeviceID uuid.UUID `db:"device_id" json:"device_id"`
	Limit    int32     `db:"limit" json:"limit"`
}

func (q *Queries) ListRecentCommandsByDevice(ctx context.Context, arg ListRecentCommandsByDeviceParams) ([]Command, error) {
	rows, err := q.db.Query(ctx, listRecentCommandsByDevice, arg.DeviceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Command{}
	for rows.Next() {
		var i Command
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Action,
			&i.Payload,
			&i.Status,
			&i.IssuedBy,
			&i.IssuedAt,
			&i.SentAt,
			&i.AckAt,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCommandAcked = `-- name: MarkCommandAcked :exec
UPDATE commands SET status = 'acked', ack_at = now() WHERE id = $1
`

func (q *Queries) MarkCommandAcked(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markCommandAcked, id)
	return err
}

const markCommandFailed = `-- name: MarkCommandFailed :exec
UPDATE commands SET status = 'failed', error_message = $2 WHERE id = $1
`

type MarkCommandFailedParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	ErrorMessage *string   `db:"error_message" json:"error_message"`
}

func (q *Queries) MarkCommandFailed(ctx context.Context, arg MarkCommandFailedParams) error {
	_, err := q.db.Exec(ctx, markCommandFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markCommandSent = `-- name: MarkCommandSent :exec
UPDATE commands SET status = 'sent', sent_at = now() WHERE id = $1
`

func (q *Queries) MarkCommandSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markCommandSent, id)
	return err
}
