// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
    zone_id, type, model, slug, name,
    mqtt_id, mqtt_password_hash, status, installed_at, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, zone_id, type, model, slug, name, mqtt_id, mqtt_password_hash, status, last_seen_at, installed_at, metadata, created_at, updated_at
`

type CreateDeviceParams struct {
	ZoneID           uuid.UUID          `db:"zone_id" json:"zone_id"`
	Type             DeviceType         `db:"type" json:"type"`
	Model            *string            `db:"model" json:"model"`
	Slug             string             `db:"slug" json:"slug"`
	Name             *string            `db:"name" json:"name"`
	MQTTID           string             `db:"mqtt_id" json:"mqtt_id"`
	MqttPasswordHash string             `db:"mqtt_password_hash" json:"mqtt_password_hash"`
	Status           DeviceStatus       `db:"status" json:"status"`
	InstalledAt      pgtype.Timestamptz `db:"installed_at" json:"installed_at"`
	Metadata         json.RawMessage    `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.ZoneID,
		arg.Type,
		arg.Model,
		arg.Slug,
		arg.Name,
		arg.MQTTID,
		arg.MqttPasswordHash,
		arg.Status,
		arg.InstalledAt,
		arg.Metadata,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ZoneID,
		&i.Type,
		&i.Model,
		&i.Slug,
		&i.Name,
		&i.MQTTID,
		&i.MqttPasswordHash,
		&i.Status,
		&i.LastSeenAt,
		&i.InstalledAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = $1
`

func (q *Queries) DeleteDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDevice, id)
	return err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, zone_id, type, model, slug, name, mqtt_id, mqtt_password_hash, status, last_seen_at, installed_at, metadata, created_at, updated_at FROM devices WHERE id = $1
`

func (q *Queries) GetDeviceByID(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ZoneID,
		&i.Type,
		&i.Model,
		&i.Slug,
		&i.Name,
		&i.MQTTID,
		&i.MqttPasswordHash,
		&i.Status,
		&i.LastSeenAt,
		&i.InstalledAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByMQTTID = `-- name: GetDeviceByMQTTID :one
SELECT id, zone_id, type, model, slug, name, mqtt_id, mqtt_password_hash, status, last_seen_at, installed_at, metadata, created_at, updated_at FROM devices WHERE mqtt_id = $1
`

func (q *Queries) GetDeviceByMQTTID(ctx context.Context, mqttID string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByMQTTID, mqttID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ZoneID,
		&i.Type,
		&i.Model,
		&i.Slug,
		&i.Name,
		&i.MQTTID,
		&i.MqttPasswordHash,
		&i.Status,
		&i.LastSeenAt,
		&i.InstalledAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDevicesBySite = `-- name: ListDevicesBySite :many
SELECT d.id, d.zone_id, d.type, d.model, d.slug, d.name, d.mqtt_id, d.mqtt_password_hash, d.status, d.last_seen_at, d.installed_at, d.metadata, d.created_at, d.updated_at
FROM devices d
JOIN zones z ON z.id = d.zone_id
WHERE z.site_id = $1
ORDER BY d.slug
`

func (q *Queries) ListDevicesBySite(ctx context.Context, siteID uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.ZoneID,
			&i.Type,
			&i.Model,
			&i.Slug,
			&i.Name,
			&i.MQTTID,
			&i.MqttPasswordHash,
			&i.Status,
			&i.LastSeenAt,
			&i.InstalledAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByTenant = `-- name: ListDevicesByTenant :many
SELECT d.id, d.zone_id, d.type, d.model, d.slug, d.name, d.mqtt_id, d.mqtt_password_hash, d.status, d.last_seen_at, d.installed_at, d.metadata, d.created_at, d.updated_at
FROM devices d
JOIN zones z ON z.id = d.zone_id
JOIN sites s ON s.id = z.site_id
WHERE s.tenant_id = $1
ORDER BY d.slug
`

func (q *Queries) ListDevicesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.ZoneID,
			&i.Type,
			&i.Model,
			&i.Slug,
			&i.Name,
			&i.MQTTID,
			&i.MqttPasswordHash,
			&i.Status,
			&i.LastSeenAt,
			&i.InstalledAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByZone = `-- name: ListDevicesByZone :many
SELECT id, zone_id, type, model, slug, name, mqtt_id, mqtt_password_hash, status, last_seen_at, installed_at, metadata, created_at, updated_at FROM devices WHERE zone_id = $1 ORDER BY slug
`

func (q *Queries) ListDevicesByZone(ctx context.Context, zoneID uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByZone, zoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.ZoneID,
			&i.Type,
			&i.Model,
			&i.Slug,
			&i.Name,
			&i.MQTTID,
			&i.MqttPasswordHash,
			&i.Status,
			&i.LastSeenAt,
			&i.InstalledAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeasurementMetadataByDevice = `-- name: ListMeasurementMetadataByDevice :many
SELECT device_id, measurement, unit, min_value, max_value, description FROM measurements_metadata WHERE device_id = $1
`

func (q *Queries) ListMeasurementMetadataByDevice(ctx context.Context, deviceID uuid.UUID) ([]MeasurementsMetadatum, error) {
	rows, err := q.db.Query(ctx, listMeasurementMetadataByDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeasurementsMetadatum{}
	for rows.Next() {
		var i MeasurementsMetadatum
		if err := rows.Scan(
			&i.DeviceID,
			&i.Measurement,
			&i.Unit,
			&i.MinValue,
			&i.MaxValue,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchDeviceLastSeen = `-- name: TouchDeviceLastSeen :exec
UPDATE devices SET last_seen_at = now(), status = 'online'
WHERE mqtt_id = $1
`

func (q *Queries) TouchDeviceLastSeen(ctx context.Context, mqttID string) error {
	_, err := q.db.Exec(ctx, touchDeviceLastSeen, mqttID)
	return err
}

const updateDeviceStatus = `-- name: UpdateDeviceStatus :exec
UPDATE devices SET status = $2, last_seen_at = $3, updated_at = now()
WHERE id = $1
`

type UpdateDeviceStatusParams struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	Status     DeviceStatus       `db:"status" json:"status"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
}

func (q *Queries) UpdateDeviceStatus(ctx context.Context, arg UpdateDeviceStatusParams) error {
	_, err := q.db.Exec(ctx, updateDeviceStatus, arg.ID, arg.Status, arg.LastSeenAt)
	return err
}

const upsertMeasurementMetadata = `-- name: UpsertMeasurementMetadata :exec
INSERT INTO measurements_metadata (device_id, measurement, unit, min_value, max_value, description)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (device_id, measurement) DO UPDATE
SET unit = EXCLUDED.unit,
    min_value = EXCLUDED.min_value,
    max_value = EXCLUDED.max_value,
    description = EXCLUDED.description
`

type UpsertMeasurementMetadataParams struct {
	DeviceID    uuid.UUID `db:"device_id" json:"device_id"`
	Measurement string    `db:"measurement" json:"measurement"`
	Unit        string    `db:"unit" json:"unit"`
	MinValue    *float64  `db:"min_value" json:"min_value"`
	MaxValue    *float64  `db:"max_value" json:"max_value"`
	Description *string   `db:"description" json:"description"`
}

func (q *Queries) UpsertMeasurementMetadata(ctx context.Context, arg UpsertMeasurementMetadataParams) error {
	_, err := q.db.Exec(ctx, upsertMeasurementMetadata,
		arg.DeviceID,
		arg.Measurement,
		arg.Unit,
		arg.MinValue,
		arg.MaxValue,
		arg.Description,
	)
	return err
}
