// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: measurements.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getLatestMeasurements = `-- name: GetLatestMeasurements :many
SELECT DISTINCT ON (measurement)
    ts, device_id, measurement, value, quality
FROM measurements
WHERE device_id = $1
ORDER BY measurement, ts DESC
`

// Dernière valeur par measurement pour un device — utilise l'index DESC.
func (q *Queries) GetLatestMeasurements(ctx context.Context, deviceID uuid.UUID) ([]Measurement, error) {
	rows, err := q.db.Query(ctx, getLatestMeasurements, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Measurement{}
	for rows.Next() {
		var i Measurement
		if err := rows.Scan(
			&i.Ts,
			&i.DeviceID,
			&i.Measurement,
			&i.Value,
			&i.Quality,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMeasurements15Min = `-- name: GetMeasurements15Min :many
SELECT bucket AS ts, avg_value, min_value, max_value, sample_count
FROM measurements_15min
WHERE device_id = $1 AND measurement = $2 AND bucket >= $3 AND bucket < $4
ORDER BY bucket ASC
`

type GetMeasurements15MinParams struct {
	DeviceID    uuid.UUID   `db:"device_id" json:"device_id"`
	Measurement string      `db:"measurement" json:"measurement"`
	Bucket      interface{} `db:"bucket" json:"bucket"`
	Bucket_2    interface{} `db:"bucket_2" json:"bucket_2"`
}

type GetMeasurements15MinRow struct {
	Ts          interface{} `db:"ts" json:"ts"`
	AvgValue    float64     `db:"avg_value" json:"avg_value"`
	MinValue    interface{} `db:"min_value" json:"min_value"`
	MaxValue    interface{} `db:"max_value" json:"max_value"`
	SampleCount int64       `db:"sample_count" json:"sample_count"`
}

func (q *Queries) GetMeasurements15Min(ctx context.Context, arg GetMeasurements15MinParams) ([]GetMeasurements15MinRow, error) {
	rows, err := q.db.Query(ctx, getMeasurements15Min,
		arg.DeviceID,
		arg.Measurement,
		arg.Bucket,
		arg.Bucket_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMeasurements15MinRow{}
	for rows.Next() {
		var i GetMeasurements15MinRow
		if err := rows.Scan(
			&i.Ts,
			&i.AvgValue,
			&i.MinValue,
			&i.MaxValue,
			&i.SampleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMeasurements1D = `-- name: GetMeasurements1D :many
SELECT bucket AS ts, avg_value, min_value, max_value, sum_value, sample_count
FROM measurements_1d
WHERE device_id = $1 AND measurement = $2 AND bucket >= $3 AND bucket < $4
ORDER BY bucket ASC
`

type GetMeasurements1DParams struct {
	DeviceID    uuid.UUID   `db:"device_id" json:"device_id"`
	Measurement string      `db:"measurement" json:"measurement"`
	Bucket      interface{} `db:"bucket" json:"bucket"`
	Bucket_2    interface{} `db:"bucket_2" json:"bucket_2"`
}

type GetMeasurements1DRow struct {
	Ts          interface{} `db:"ts" json:"ts"`
	AvgValue    float64     `db:"avg_value" json:"avg_value"`
	MinValue    interface{} `db:"min_value" json:"min_value"`
	MaxValue    interface{} `db:"max_value" json:"max_value"`
	SumValue    int64       `db:"sum_value" json:"sum_value"`
	SampleCount int64       `db:"sample_count" json:"sample_count"`
}

func (q *Queries) GetMeasurements1D(ctx context.Context, arg GetMeasurements1DParams) ([]GetMeasurements1DRow, error) {
	rows, err := q.db.Query(ctx, getMeasurements1D,
		arg.DeviceID,
		arg.Measurement,
		arg.Bucket,
		arg.Bucket_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMeasurements1DRow{}
	for rows.Next() {
		var i GetMeasurements1DRow
		if err := rows.Scan(
			&i.Ts,
			&i.AvgValue,
			&i.MinValue,
			&i.MaxValue,
			&i.SumValue,
			&i.SampleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMeasurements1H = `-- name: GetMeasurements1H :many
SELECT bucket AS ts, avg_value, min_value, max_value, sample_count
FROM measurements_1h
WHERE device_id = $1 AND measurement = $2 AND bucket >= $3 AND bucket < $4
ORDER BY bucket ASC
`

type GetMeasurements1HParams struct {
	DeviceID    uuid.UUID   `db:"device_id" json:"device_id"`
	Measurement string      `db:"measurement" json:"measurement"`
	Bucket      interface{} `db:"bucket" json:"bucket"`
	Bucket_2    interface{} `db:"bucket_2" json:"bucket_2"`
}

type GetMeasurements1HRow struct {
	Ts          interface{} `db:"ts" json:"ts"`
	AvgValue    float64     `db:"avg_value" json:"avg_value"`
	MinValue    interface{} `db:"min_value" json:"min_value"`
	MaxValue    interface{} `db:"max_value" json:"max_value"`
	SampleCount int64       `db:"sample_count" json:"sample_count"`
}

func (q *Queries) GetMeasurements1H(ctx context.Context, arg GetMeasurements1HParams) ([]GetMeasurements1HRow, error) {
	rows, err := q.db.Query(ctx, getMeasurements1H,
		arg.DeviceID,
		arg.Measurement,
		arg.Bucket,
		arg.Bucket_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMeasurements1HRow{}
	for rows.Next() {
		var i GetMeasurements1HRow
		if err := rows.Scan(
			&i.Ts,
			&i.AvgValue,
			&i.MinValue,
			&i.MaxValue,
			&i.SampleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMeasurements1Min = `-- name: GetMeasurements1Min :many
SELECT bucket AS ts, avg_value, min_value, max_value, sample_count
FROM measurements_1min
WHERE device_id = $1 AND measurement = $2 AND bucket >= $3 AND bucket < $4
ORDER BY bucket ASC
`

type GetMeasurements1MinParams struct {
	DeviceID    uuid.UUID   `db:"device_id" json:"device_id"`
	Measurement string      `db:"measurement" json:"measurement"`
	Bucket      interface{} `db:"bucket" json:"bucket"`
	Bucket_2    interface{} `db:"bucket_2" json:"bucket_2"`
}

type GetMeasurements1MinRow struct {
	Ts          interface{} `db:"ts" json:"ts"`
	AvgValue    float64     `db:"avg_value" json:"avg_value"`
	MinValue    interface{} `db:"min_value" json:"min_value"`
	MaxValue    interface{} `db:"max_value" json:"max_value"`
	SampleCount int64       `db:"sample_count" json:"sample_count"`
}

func (q *Queries) GetMeasurements1Min(ctx context.Context, arg GetMeasurements1MinParams) ([]GetMeasurements1MinRow, error) {
	rows, err := q.db.Query(ctx, getMeasurements1Min,
		arg.DeviceID,
		arg.Measurement,
		arg.Bucket,
		arg.Bucket_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMeasurements1MinRow{}
	for rows.Next() {
		var i GetMeasurements1MinRow
		if err := rows.Scan(
			&i.Ts,
			&i.AvgValue,
			&i.MinValue,
			&i.MaxValue,
			&i.SampleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMeasurementsRaw = `-- name: GetMeasurementsRaw :many
SELECT ts, value, quality
FROM measurements
WHERE device_id = $1
  AND measurement = $2
  AND ts >= $3
  AND ts <  $4
ORDER BY ts ASC
`

type GetMeasurementsRawParams struct {
	DeviceID    uuid.UUID `db:"device_id" json:"device_id"`
	Measurement string    `db:"measurement" json:"measurement"`
	Ts          time.Time `db:"ts" json:"ts"`
	Ts_2        time.Time `db:"ts_2" json:"ts_2"`
}

type GetMeasurementsRawRow struct {
	Ts      time.Time          `db:"ts" json:"ts"`
	Value   float64            `db:"value" json:"value"`
	Quality MeasurementQuality `db:"quality" json:"quality"`
}

func (q *Queries) GetMeasurementsRaw(ctx context.Context, arg GetMeasurementsRawParams) ([]GetMeasurementsRawRow, error) {
	rows, err := q.db.Query(ctx, getMeasurementsRaw,
		arg.DeviceID,
		arg.Measurement,
		arg.Ts,
		arg.Ts_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMeasurementsRawRow{}
	for rows.Next() {
		var i GetMeasurementsRawRow
		if err := rows.Scan(&i.Ts, &i.Value, &i.Quality); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMeasurement = `-- name: InsertMeasurement :exec
INSERT INTO measurements (ts, device_id, measurement, value, quality)
VALUES ($1, $2, $3, $4, $5)
`

type InsertMeasurementParams struct {
	Ts          time.Time          `db:"ts" json:"ts"`
	DeviceID    uuid.UUID          `db:"device_id" json:"device_id"`
	Measurement string             `db:"measurement" json:"measurement"`
	Value       float64            `db:"value" json:"value"`
	Quality     MeasurementQuality `db:"quality" json:"quality"`
}

// L'ingestor utilise CopyFrom pour le bulk ; cette query reste utile pour les tests.
func (q *Queries) InsertMeasurement(ctx context.Context, arg InsertMeasurementParams) error {
	_, err := q.db.Exec(ctx, insertMeasurement,
		arg.Ts,
		arg.DeviceID,
		arg.Measurement,
		arg.Value,
		arg.Quality,
	)
	return err
}
