// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CommandStatus string

const (
	CommandStatusPending CommandStatus = "pending"
	CommandStatusSent    CommandStatus = "sent"
	CommandStatusAcked   CommandStatus = "acked"
	CommandStatusFailed  CommandStatus = "failed"
	CommandStatusTimeout CommandStatus = "timeout"
)

func (e *CommandStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CommandStatus(s)
	case string:
		*e = CommandStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CommandStatus: %T", src)
	}
	return nil
}

type NullCommandStatus struct {
	CommandStatus CommandStatus `json:"command_status"`
	Valid         bool          `json:"valid"` // Valid is true if CommandStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCommandStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CommandStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CommandStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCommandStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CommandStatus), nil
}

func (e CommandStatus) Valid() bool {
	switch e {
	case CommandStatusPending,
		CommandStatusSent,
		CommandStatusAcked,
		CommandStatusFailed,
		CommandStatusTimeout:
		return true
	}
	return false
}

func AllCommandStatusValues() []CommandStatus {
	return []CommandStatus{
		CommandStatusPending,
		CommandStatusSent,
		CommandStatusAcked,
		CommandStatusFailed,
		CommandStatusTimeout,
	}
}

type DeviceStatus string

const (
	DeviceStatusProvisioned DeviceStatus = "provisioned"
	DeviceStatusOnline      DeviceStatus = "online"
	DeviceStatusOffline     DeviceStatus = "offline"
	DeviceStatusDisabled    DeviceStatus = "disabled"
)

func (e *DeviceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeviceStatus(s)
	case string:
		*e = DeviceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeviceStatus: %T", src)
	}
	return nil
}

type NullDeviceStatus struct {
	DeviceStatus DeviceStatus `json:"device_status"`
	Valid        bool         `json:"valid"` // Valid is true if DeviceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeviceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeviceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeviceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeviceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeviceStatus), nil
}

func (e DeviceStatus) Valid() bool {
	switch e {
	case DeviceStatusProvisioned,
		DeviceStatusOnline,
		DeviceStatusOffline,
		DeviceStatusDisabled:
		return true
	}
	return false
}

func AllDeviceStatusValues() []DeviceStatus {
	return []DeviceStatus{
		DeviceStatusProvisioned,
		DeviceStatusOnline,
		DeviceStatusOffline,
		DeviceStatusDisabled,
	}
}

type DeviceType string

const (
	DeviceTypeEnvironment DeviceType = "environment"
	DeviceTypePresence    DeviceType = "presence"
	DeviceTypeActuator    DeviceType = "actuator"
	DeviceTypeLinky       DeviceType = "linky"
	DeviceTypeMeter       DeviceType = "meter"
	DeviceTypeGateway     DeviceType = "gateway"
)

func (e *DeviceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeviceType(s)
	case string:
		*e = DeviceType(s)
	default:
		return fmt.Errorf("unsupported scan type for DeviceType: %T", src)
	}
	return nil
}

type NullDeviceType struct {
	DeviceType DeviceType `json:"device_type"`
	Valid      bool       `json:"valid"` // Valid is true if DeviceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeviceType) Scan(value interface{}) error {
	if value == nil {
		ns.DeviceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeviceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeviceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeviceType), nil
}

func (e DeviceType) Valid() bool {
	switch e {
	case DeviceTypeEnvironment,
		DeviceTypePresence,
		DeviceTypeActuator,
		DeviceTypeLinky,
		DeviceTypeMeter,
		DeviceTypeGateway:
		return true
	}
	return false
}

func AllDeviceTypeValues() []DeviceType {
	return []DeviceType{
		DeviceTypeEnvironment,
		DeviceTypePresence,
		DeviceTypeActuator,
		DeviceTypeLinky,
		DeviceTypeMeter,
		DeviceTypeGateway,
	}
}

type MeasurementQuality string

const (
	MeasurementQualityGood      MeasurementQuality = "good"
	MeasurementQualityUncertain MeasurementQuality = "uncertain"
	MeasurementQualityBad       MeasurementQuality = "bad"
)

func (e *MeasurementQuality) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MeasurementQuality(s)
	case string:
		*e = MeasurementQuality(s)
	default:
		return fmt.Errorf("unsupported scan type for MeasurementQuality: %T", src)
	}
	return nil
}

type NullMeasurementQuality struct {
	MeasurementQuality MeasurementQuality `json:"measurement_quality"`
	Valid              bool               `json:"valid"` // Valid is true if MeasurementQuality is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMeasurementQuality) Scan(value interface{}) error {
	if value == nil {
		ns.MeasurementQuality, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MeasurementQuality.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMeasurementQuality) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MeasurementQuality), nil
}

func (e MeasurementQuality) Valid() bool {
	switch e {
	case MeasurementQualityGood,
		MeasurementQualityUncertain,
		MeasurementQualityBad:
		return true
	}
	return false
}

func AllMeasurementQualityValues() []MeasurementQuality {
	return []MeasurementQuality{
		MeasurementQualityGood,
		MeasurementQualityUncertain,
		MeasurementQualityBad,
	}
}

type RuleExecutionResult string

const (
	RuleExecutionResultSuccess RuleExecutionResult = "success"
	RuleExecutionResultPartial RuleExecutionResult = "partial"
	RuleExecutionResultFailure RuleExecutionResult = "failure"
	RuleExecutionResultSkipped RuleExecutionResult = "skipped"
)

func (e *RuleExecutionResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RuleExecutionResult(s)
	case string:
		*e = RuleExecutionResult(s)
	default:
		return fmt.Errorf("unsupported scan type for RuleExecutionResult: %T", src)
	}
	return nil
}

type NullRuleExecutionResult struct {
	RuleExecutionResult RuleExecutionResult `json:"rule_execution_result"`
	Valid               bool                `json:"valid"` // Valid is true if RuleExecutionResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRuleExecutionResult) Scan(value interface{}) error {
	if value == nil {
		ns.RuleExecutionResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RuleExecutionResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRuleExecutionResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RuleExecutionResult), nil
}

func (e RuleExecutionResult) Valid() bool {
	switch e {
	case RuleExecutionResultSuccess,
		RuleExecutionResultPartial,
		RuleExecutionResultFailure,
		RuleExecutionResultSkipped:
		return true
	}
	return false
}

func AllRuleExecutionResultValues() []RuleExecutionResult {
	return []RuleExecutionResult{
		RuleExecutionResultSuccess,
		RuleExecutionResultPartial,
		RuleExecutionResultFailure,
		RuleExecutionResultSkipped,
	}
}

type UserRole string

const (
	UserRoleAdmin   UserRole = "admin"
	UserRoleManager UserRole = "manager"
	UserRoleViewer  UserRole = "viewer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

func (e UserRole) Valid() bool {
	switch e {
	case UserRoleAdmin,
		UserRoleManager,
		UserRoleViewer:
		return true
	}
	return false
}

func AllUserRoleValues() []UserRole {
	return []UserRole{
		UserRoleAdmin,
		UserRoleManager,
		UserRoleViewer,
	}
}

type Command struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	DeviceID     uuid.UUID          `db:"device_id" json:"device_id"`
	Action       string             `db:"action" json:"action"`
	Payload      json.RawMessage    `db:"payload" json:"payload"`
	Status       CommandStatus      `db:"status" json:"status"`
	IssuedBy     pgtype.UUID        `db:"issued_by" json:"issued_by"`
	IssuedAt     time.Time          `db:"issued_at" json:"issued_at"`
	SentAt       pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
	AckAt        pgtype.Timestamptz `db:"ack_at" json:"ack_at"`
	ErrorMessage *string            `db:"error_message" json:"error_message"`
}

type Device struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	ZoneID           uuid.UUID          `db:"zone_id" json:"zone_id"`
	Type             DeviceType         `db:"type" json:"type"`
	Model            *string            `db:"model" json:"model"`
	Slug             string             `db:"slug" json:"slug"`
	Name             *string            `db:"name" json:"name"`
	MQTTID           string             `db:"mqtt_id" json:"mqtt_id"`
	MqttPasswordHash string             `db:"mqtt_password_hash" json:"mqtt_password_hash"`
	Status           DeviceStatus       `db:"status" json:"status"`
	LastSeenAt       pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	InstalledAt      pgtype.Timestamptz `db:"installed_at" json:"installed_at"`
	Metadata         json.RawMessage    `db:"metadata" json:"metadata"`
	CreatedAt        time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time          `db:"updated_at" json:"updated_at"`
}

type Measurement struct {
	Ts          time.Time          `db:"ts" json:"ts"`
	DeviceID    uuid.UUID          `db:"device_id" json:"device_id"`
	Measurement string             `db:"measurement" json:"measurement"`
	Value       float64            `db:"value" json:"value"`
	Quality     MeasurementQuality `db:"quality" json:"quality"`
}

type Measurements15min struct {
	Bucket      interface{} `db:"bucket" json:"bucket"`
	DeviceID    uuid.UUID   `db:"device_id" json:"device_id"`
	Measurement string      `db:"measurement" json:"measurement"`
	AvgValue    float64     `db:"avg_value" json:"avg_value"`
	MinValue    interface{} `db:"min_value" json:"min_value"`
	MaxValue    interface{} `db:"max_value" json:"max_value"`
	SampleCount int64       `db:"sample_count" json:"sample_count"`
}

type Measurements1d struct {
	Bucket      interface{} `db:"bucket" json:"bucket"`
	DeviceID    uuid.UUID   `db:"device_id" json:"device_id"`
	Measurement string      `db:"measurement" json:"measurement"`
	AvgValue    float64     `db:"avg_value" json:"avg_value"`
	MinValue    interface{} `db:"min_value" json:"min_value"`
	MaxValue    interface{} `db:"max_value" json:"max_value"`
	SumValue    int64       `db:"sum_value" json:"sum_value"`
	SampleCount int64       `db:"sample_count" json:"sample_count"`
}

type Measurements1h struct {
	Bucket      interface{} `db:"bucket" json:"bucket"`
	DeviceID    uuid.UUID   `db:"device_id" json:"device_id"`
	Measurement string      `db:"measurement" json:"measurement"`
	AvgValue    float64     `db:"avg_value" json:"avg_value"`
	MinValue    interface{} `db:"min_value" json:"min_value"`
	MaxValue    interface{} `db:"max_value" json:"max_value"`
	SampleCount int64       `db:"sample_count" json:"sample_count"`
}

type Measurements1min struct {
	Bucket      interface{} `db:"bucket" json:"bucket"`
	DeviceID    uuid.UUID   `db:"device_id" json:"device_id"`
	Measurement string      `db:"measurement" json:"measurement"`
	AvgValue    float64     `db:"avg_value" json:"avg_value"`
	MinValue    interface{} `db:"min_value" json:"min_value"`
	MaxValue    interface{} `db:"max_value" json:"max_value"`
	SampleCount int64       `db:"sample_count" json:"sample_count"`
}

type MeasurementsMetadatum struct {
	DeviceID    uuid.UUID `db:"device_id" json:"device_id"`
	Measurement string    `db:"measurement" json:"measurement"`
	Unit        string    `db:"unit" json:"unit"`
	MinValue    *float64  `db:"min_value" json:"min_value"`
	MaxValue    *float64  `db:"max_value" json:"max_value"`
	Description *string   `db:"description" json:"description"`
}

type Rule struct {
	ID          uuid.UUID       `db:"id" json:"id"`
	TenantID    uuid.UUID       `db:"tenant_id" json:"tenant_id"`
	Name        string          `db:"name" json:"name"`
	Description *string         `db:"description" json:"description"`
	Enabled     bool            `db:"enabled" json:"enabled"`
	Definition  json.RawMessage `db:"definition" json:"definition"`
	CreatedBy   pgtype.UUID     `db:"created_by" json:"created_by"`
	CreatedAt   time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time       `db:"updated_at" json:"updated_at"`
}

type RuleExecution struct {
	ID           uuid.UUID           `db:"id" json:"id"`
	RuleID       uuid.UUID           `db:"rule_id" json:"rule_id"`
	TriggeredAt  time.Time           `db:"triggered_at" json:"triggered_at"`
	ActionTaken  json.RawMessage     `db:"action_taken" json:"action_taken"`
	Result       RuleExecutionResult `db:"result" json:"result"`
	ErrorMessage *string             `db:"error_message" json:"error_message"`
	LatencyMs    int32               `db:"latency_ms" json:"latency_ms"`
}

type Site struct {
	ID        uuid.UUID `db:"id" json:"id"`
	TenantID  uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Slug      string    `db:"slug" json:"slug"`
	Name      string    `db:"name" json:"name"`
	Address   *string   `db:"address" json:"address"`
	Lat       *float64  `db:"lat" json:"lat"`
	Lng       *float64  `db:"lng" json:"lng"`
	Timezone  string    `db:"timezone" json:"timezone"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type Tenant struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Slug      string    `db:"slug" json:"slug"`
	Name      string    `db:"name" json:"name"`
	Plan      string    `db:"plan" json:"plan"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	TenantID     uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	Role         UserRole           `db:"role" json:"role"`
	FullName     *string            `db:"full_name" json:"full_name"`
	LastLoginAt  pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt    time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time          `db:"updated_at" json:"updated_at"`
}

type Zone struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	SiteID       uuid.UUID   `db:"site_id" json:"site_id"`
	ParentZoneID pgtype.UUID `db:"parent_zone_id" json:"parent_zone_id"`
	Slug         string      `db:"slug" json:"slug"`
	Name         string      `db:"name" json:"name"`
	CreatedAt    time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time   `db:"updated_at" json:"updated_at"`
}
