// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCommand(ctx context.Context, arg CreateCommandParams) (Command, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error)
	CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateZone(ctx context.Context, arg CreateZoneParams) (Zone, error)
	DeleteDevice(ctx context.Context, id uuid.UUID) error
	DeleteRule(ctx context.Context, id uuid.UUID) error
	DeleteSite(ctx context.Context, id uuid.UUID) error
	DeleteTenant(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteZone(ctx context.Context, id uuid.UUID) error
	GetCommandByID(ctx context.Context, id uuid.UUID) (Command, error)
	GetDeviceByID(ctx context.Context, id uuid.UUID) (Device, error)
	GetDeviceByMQTTID(ctx context.Context, mqttID string) (Device, error)
	// Dernière valeur par measurement pour un device — utilise l'index DESC.
	GetLatestMeasurements(ctx context.Context, deviceID uuid.UUID) ([]Measurement, error)
	GetMeasurements15Min(ctx context.Context, arg GetMeasurements15MinParams) ([]GetMeasurements15MinRow, error)
	GetMeasurements1D(ctx context.Context, arg GetMeasurements1DParams) ([]GetMeasurements1DRow, error)
	GetMeasurements1H(ctx context.Context, arg GetMeasurements1HParams) ([]GetMeasurements1HRow, error)
	GetMeasurements1Min(ctx context.Context, arg GetMeasurements1MinParams) ([]GetMeasurements1MinRow, error)
	GetMeasurementsRaw(ctx context.Context, arg GetMeasurementsRawParams) ([]GetMeasurementsRawRow, error)
	GetRuleByID(ctx context.Context, id uuid.UUID) (Rule, error)
	GetSiteByID(ctx context.Context, id uuid.UUID) (Site, error)
	GetSiteBySlug(ctx context.Context, arg GetSiteBySlugParams) (Site, error)
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetZoneByID(ctx context.Context, id uuid.UUID) (Zone, error)
	// L'ingestor utilise CopyFrom pour le bulk ; cette query reste utile pour les tests.
	InsertMeasurement(ctx context.Context, arg InsertMeasurementParams) error
	InsertRuleExecution(ctx context.Context, arg InsertRuleExecutionParams) (RuleExecution, error)
	ListChildZones(ctx context.Context, parentZoneID pgtype.UUID) ([]Zone, error)
	ListDevicesBySite(ctx context.Context, siteID uuid.UUID) ([]Device, error)
	ListDevicesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Device, error)
	ListDevicesByZone(ctx context.Context, zoneID uuid.UUID) ([]Device, error)
	ListEnabledRules(ctx context.Context) ([]Rule, error)
	ListMeasurementMetadataByDevice(ctx context.Context, deviceID uuid.UUID) ([]MeasurementsMetadatum, error)
	ListRecentCommandsByDevice(ctx context.Context, arg ListRecentCommandsByDeviceParams) ([]Command, error)
	ListRuleExecutions(ctx context.Context, arg ListRuleExecutionsParams) ([]RuleExecution, error)
	ListRulesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Rule, error)
	ListSitesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Site, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	ListUsersByTenant(ctx context.Context, tenantID uuid.UUID) ([]User, error)
	ListZonesBySite(ctx context.Context, siteID uuid.UUID) ([]Zone, error)
	MarkCommandAcked(ctx context.Context, id uuid.UUID) error
	MarkCommandFailed(ctx context.Context, arg MarkCommandFailedParams) error
	MarkCommandSent(ctx context.Context, id uuid.UUID) error
	SetRuleEnabled(ctx context.Context, arg SetRuleEnabledParams) error
	TouchDeviceLastSeen(ctx context.Context, mqttID string) error
	TouchUserLogin(ctx context.Context, id uuid.UUID) error
	UpdateDeviceStatus(ctx context.Context, arg UpdateDeviceStatusParams) error
	UpdateRule(ctx context.Context, arg UpdateRuleParams) (Rule, error)
	UpdateSite(ctx context.Context, arg UpdateSiteParams) (Site, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateZone(ctx context.Context, arg UpdateZoneParams) (Zone, error)
	UpsertMeasurementMetadata(ctx context.Context, arg UpsertMeasurementMetadataParams) error
}

var _ Querier = (*Queries)(nil)
