// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rules.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRule = `-- name: CreateRule :one
INSERT INTO rules (tenant_id, name, description, enabled, definition, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, description, enabled, definition, created_by, created_at, updated_at
`

type CreateRuleParams struct {
	TenantID    uuid.UUID       `db:"tenant_id" json:"tenant_id"`
	Name        string          `db:"name" json:"name"`
	Description *string         `db:"description" json:"description"`
	Enabled     bool            `db:"enabled" json:"enabled"`
	Definition  json.RawMessage `db:"definition" json:"definition"`
	CreatedBy   pgtype.UUID     `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, createRule,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.Enabled,
		arg.Definition,
		arg.CreatedBy,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.Definition,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM rules WHERE id = $1
`

func (q *Queries) DeleteRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRule, id)
	return err
}

const getRuleByID = `-- name: GetRuleByID :one
SELECT id, tenant_id, name, description, enabled, definition, created_by, created_at, updated_at FROM rules WHERE id = $1
`

func (q *Queries) GetRuleByID(ctx context.Context, id uuid.UUID) (Rule, error) {
	row := q.db.QueryRow(ctx, getRuleByID, id)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.Definition,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRuleExecution = `-- name: InsertRuleExecution :one
INSERT INTO rule_executions (rule_id, action_taken, result, error_message, latency_ms)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, rule_id, triggered_at, action_taken, result, error_message, latency_ms
`

type InsertRuleExecutionParams struct {
	RuleID       uuid.UUID           `db:"rule_id" json:"rule_id"`
	ActionTaken  json.RawMessage     `db:"action_taken" json:"action_taken"`
	Result       RuleExecutionResult `db:"result" json:"result"`
	ErrorMessage *string             `db:"error_message" json:"error_message"`
	LatencyMs    int32               `db:"latency_ms" json:"latency_ms"`
}

func (q *Queries) InsertRuleExecution(ctx context.Context, arg InsertRuleExecutionParams) (RuleExecution, error) {
	row := q.db.QueryRow(ctx, insertRuleExecution,
		arg.RuleID,
		arg.ActionTaken,
		arg.Result,
		arg.ErrorMessage,
		arg.LatencyMs,
	)
	var i RuleExecution
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.TriggeredAt,
		&i.ActionTaken,
		&i.Result,
		&i.ErrorMessage,
		&i.LatencyMs,
	)
	return i, err
}

const listEnabledRules = `-- name: ListEnabledRules :many
SELECT id, tenant_id, name, description, enabled, definition, created_by, created_at, updated_at FROM rules WHERE enabled = TRUE ORDER BY created_at DESC
`

func (q *Queries) ListEnabledRules(ctx context.Context) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listEnabledRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rule{}
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Enabled,
			&i.Definition,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuleExecutions = `-- name: ListRuleExecutions :many
SELECT id, rule_id, triggered_at, action_taken, result, error_message, latency_ms FROM rule_executions
WHERE rule_id = $1
ORDER BY triggered_at DESC
LIMIT $2
`

type ListRuleExecutionsParams struct {
	RuleID uuid.UUID `db:"rule_id" json:"rule_id"`
	Limit  int32     `db:"limit" json:"limit"`
}

func (q *Queries) ListRuleExecutions(ctx context.Context, arg ListRuleExecutionsParams) ([]RuleExecution, error) {
	rows, err := q.db.Query(ctx, listRuleExecutions, arg.RuleID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuleExecution{}
	for rows.Next() {
		var i RuleExecution
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.TriggeredAt,
			&i.ActionTaken,
			&i.Result,
			&i.ErrorMessage,
			&i.LatencyMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRulesByTenant = `-- name: ListRulesByTenant :many
SELECT id, tenant_id, name, description, enabled, definition, created_by, created_at, updated_at FROM rules WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListRulesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listRulesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rule{}
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Enabled,
			&i.Definition,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRuleEnabled = `-- name: SetRuleEnabled :exec
UPDATE rules SET enabled = $2, updated_at = now() WHERE id = $1
`

type SetRuleEnabledParams struct {
	ID      uuid.UUID `db:"id" json:"id"`
	Enabled bool      `db:"enabled" json:"enabled"`
}

func (q *Queries) SetRuleEnabled(ctx context.Context, arg SetRuleEnabledParams) error {
	_, err := q.db.Exec(ctx, setRuleEnabled, arg.ID, arg.Enabled)
	return err
}

const updateRule = `-- name: UpdateRule :one
UPDATE rules
SET name = $2, description = $3, enabled = $4, definition = $5, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, name, description, enabled, definition, created_by, created_at, updated_at
`

type UpdateRuleParams struct {
	ID          uuid.UUID       `db:"id" json:"id"`
	Name        string          `db:"name" json:"name"`
	Description *string         `db:"description" json:"description"`
	Enabled     bool            `db:"enabled" json:"enabled"`
	Definition  json.RawMessage `db:"definition" json:"definition"`
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, updateRule,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Enabled,
		arg.Definition,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.Definition,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
