// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sites.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSite = `-- name: CreateSite :one
INSERT INTO sites (tenant_id, slug, name, address, lat, lng, timezone)
VALUES ($1, $2, $3, $4, $5, $6, COALESCE($7, 'Africa/Ouagadougou'))
RETURNING id, tenant_id, slug, name, address, lat, lng, timezone, created_at, updated_at
`

type CreateSiteParams struct {
	TenantID uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	Slug     string      `db:"slug" json:"slug"`
	Name     string      `db:"name" json:"name"`
	Address  *string     `db:"address" json:"address"`
	Lat      *float64    `db:"lat" json:"lat"`
	Lng      *float64    `db:"lng" json:"lng"`
	Timezone interface{} `db:"timezone" json:"timezone"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.TenantID,
		arg.Slug,
		arg.Name,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.Timezone,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSite = `-- name: DeleteSite :exec
DELETE FROM sites WHERE id = $1
`

func (q *Queries) DeleteSite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSite, id)
	return err
}

const getSiteByID = `-- name: GetSiteByID :one
SELECT id, tenant_id, slug, name, address, lat, lng, timezone, created_at, updated_at FROM sites WHERE id = $1
`

func (q *Queries) GetSiteByID(ctx context.Context, id uuid.UUID) (Site, error) {
	row := q.db.QueryRow(ctx, getSiteByID, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteBySlug = `-- name: GetSiteBySlug :one
SELECT id, tenant_id, slug, name, address, lat, lng, timezone, created_at, updated_at FROM sites WHERE tenant_id = $1 AND slug = $2
`

type GetSiteBySlugParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Slug     string    `db:"slug" json:"slug"`
}

func (q *Queries) GetSiteBySlug(ctx context.Context, arg GetSiteBySlugParams) (Site, error) {
	row := q.db.QueryRow(ctx, getSiteBySlug, arg.TenantID, arg.Slug)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSitesByTenant = `-- name: ListSitesByTenant :many
SELECT id, tenant_id, slug, name, address, lat, lng, timezone, created_at, updated_at FROM sites WHERE tenant_id = $1 ORDER BY name
`

func (q *Queries) ListSitesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Site, error) {
	rows, err := q.db.Query(ctx, listSitesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Name,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSite = `-- name: UpdateSite :one
UPDATE sites
SET name = $2, address = $3, lat = $4, lng = $5, timezone = $6, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, slug, name, address, lat, lng, timezone, created_at, updated_at
`

type UpdateSiteParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	Name     string    `db:"name" json:"name"`
	Address  *string   `db:"address" json:"address"`
	Lat      *float64  `db:"lat" json:"lat"`
	Lng      *float64  `db:"lng" json:"lng"`
	Timezone string    `db:"timezone" json:"timezone"`
}

func (q *Queries) UpdateSite(ctx context.Context, arg UpdateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, updateSite,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.Timezone,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
