// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: zones.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createZone = `-- name: CreateZone :one
INSERT INTO zones (site_id, parent_zone_id, slug, name)
VALUES ($1, $2, $3, $4)
RETURNING id, site_id, parent_zone_id, slug, name, created_at, updated_at
`

type CreateZoneParams struct {
	SiteID       uuid.UUID   `db:"site_id" json:"site_id"`
	ParentZoneID pgtype.UUID `db:"parent_zone_id" json:"parent_zone_id"`
	Slug         string      `db:"slug" json:"slug"`
	Name         string      `db:"name" json:"name"`
}

func (q *Queries) CreateZone(ctx context.Context, arg CreateZoneParams) (Zone, error) {
	row := q.db.QueryRow(ctx, createZone,
		arg.SiteID,
		arg.ParentZoneID,
		arg.Slug,
		arg.Name,
	)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ParentZoneID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteZone = `-- name: DeleteZone :exec
DELETE FROM zones WHERE id = $1
`

func (q *Queries) DeleteZone(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteZone, id)
	return err
}

const getZoneByID = `-- name: GetZoneByID :one
SELECT id, site_id, parent_zone_id, slug, name, created_at, updated_at FROM zones WHERE id = $1
`

func (q *Queries) GetZoneByID(ctx context.Context, id uuid.UUID) (Zone, error) {
	row := q.db.QueryRow(ctx, getZoneByID, id)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ParentZoneID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChildZones = `-- name: ListChildZones :many
SELECT id, site_id, parent_zone_id, slug, name, created_at, updated_at FROM zones WHERE parent_zone_id = $1 ORDER BY name
`

func (q *Queries) ListChildZones(ctx context.Context, parentZoneID pgtype.UUID) ([]Zone, error) {
	rows, err := q.db.Query(ctx, listChildZones, parentZoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Zone{}
	for rows.Next() {
		var i Zone
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.ParentZoneID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZonesBySite = `-- name: ListZonesBySite :many
SELECT id, site_id, parent_zone_id, slug, name, created_at, updated_at FROM zones WHERE site_id = $1 ORDER BY name
`

func (q *Queries) ListZonesBySite(ctx context.Context, siteID uuid.UUID) ([]Zone, error) {
	rows, err := q.db.Query(ctx, listZonesBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Zone{}
	for rows.Next() {
		var i Zone
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.ParentZoneID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateZone = `-- name: UpdateZone :one
UPDATE zones SET name = $2, parent_zone_id = $3, updated_at = now()
WHERE id = $1
RETURNING id, site_id, parent_zone_id, slug, name, created_at, updated_at
`

type UpdateZoneParams struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	Name         string      `db:"name" json:"name"`
	ParentZoneID pgtype.UUID `db:"parent_zone_id" json:"parent_zone_id"`
}

func (q *Queries) UpdateZone(ctx context.Context, arg UpdateZoneParams) (Zone, error) {
	row := q.db.QueryRow(ctx, updateZone, arg.ID, arg.Name, arg.ParentZoneID)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ParentZoneID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
