ALTER TABLE zones DROP COLUMN IF EXISTS geometry;
ALTER TABLE zones DROP COLUMN IF EXISTS color;
ALTER TABLE zones DROP COLUMN IF EXISTS icon;
ALTER TABLE zones DROP COLUMN IF EXISTS description;
ALTER TABLE zones DROP COLUMN IF EXISTS kind;
DROP TYPE IF EXISTS zone_kind;
